# This pipeline uses Terraform to create/update a Self-Hosted Pipeline Agent

pool:
  vmImage: 'ubuntu-latest'


variables:
  #destroyAgentIfExists: false # defined as hidden variable
  scriptDirectory: '$(System.DefaultWorkingDirectory)/scripts'
  terraformDirectory: '$(System.DefaultWorkingDirectory)/terraform'
  terraformWorkspace: 'cd'
  sshPublicKeyFile: 'id_rsa.pub'

  # Terraform backend variables
  # terraformBackendResourceGroup: # Defined as secret variable
  # terraformBackendStorageAccount: # Defined as secret variable
  terraformBackendContainer: 'pipelineagents'
  terraformBackendBlob: 'terraform.tfstate'

  # Terraform project variables
  TF_VAR_pipeline_agent_name: 'ubuntu1804-agent'
  TF_VAR_pipeline_agent_pool: 'Ubuntu'
  TF_VAR_pipeline_resource_group: 'PipelineAgents'
  TF_VAR_ssh_public_key: 'id_rsa.pub' # Key will be downloaded in terraform directory


steps:
- task: DownloadSecureFile@1
  displayName: 'Download SSH Public Key'
  inputs:
    secureFile: '$(sshPublicKeyFile)'

- pwsh: |
   foreach ($file in $(Get-ChildItem Env:*SECUREFILEPATH))
   {
       Copy-Item $file.Value '$(terraformDirectory)'
   }
  displayName: 'Copy Secure Files'

- task: AzureCLI@2
  displayName: 'Disable agent(s)'
  name: 'agentConfig'
  enabled: true
  inputs:
    azureSubscription: '$(subscriptionConnection)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #$DebugPreference="Continue"
      #$InformationPreference="Continue"
      ./update_agent_status.ps1 -Enabled:$false -AgentPoolName $(TF_VAR_pipeline_agent_pool) -AgentNamePrefix $(TF_VAR_pipeline_agent_name) -Token "$(System.AccessToken)"
    addSpnToEnvironment: true
    useGlobalConfig: true
    workingDirectory: '$(scriptDirectory)'
  env:
    # Use Pipeline token to access Azure DevOps
    AZURE_DEVOPS_EXT_PAT: '$(System.AccessToken)'

- pwsh: |
   $terraformVersion = Get-Content "$(terraformDirectory)/.terraform-version"
   Write-Host "##vso[task.setvariable variable=version;isOutput=true]$terraformVersion"
  displayName: 'Determine Terraform version to use'
  name: terraformConfig

- task: TerraformInstaller@0
  displayName: 'Download desired Terraform version'
  inputs:
    terraformVersion: '$(terraformConfig.version)'

- task: AzureCLI@2
  displayName: 'Terraforming'
  enabled: true
  inputs:
    azureSubscription: '$(subscriptionConnection)'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
     # Use Pipeline Service Principal and Service Connection to configure Terraform azurerm provider
     $env:ARM_CLIENT_ID=$env:servicePrincipalId
     $env:ARM_CLIENT_SECRET=$env:servicePrincipalKey
     $env:ARM_SUBSCRIPTION_ID=$(az account show --query id | tr -d '\"')
     $env:ARM_TENANT_ID=$env:tenantId

     # Fix case of environment variables mangled by Azure Pipeline Agent
     foreach ($tfvar in $(Get-ChildItem Env:TF_VAR_*)) {
         $properCaseName = $tfvar.Name.Substring(0,7) + $tfvar.Name.Substring(7).ToLowerInvariant()
         Invoke-Expression "`$env:$properCaseName = `$env:$($tfvar.Name)"  
     }
     # List environment variables (debug)
     Get-ChildItem -Path Env: -Recurse -Include ARM_*,AZURE_*,TF_* | Sort-Object -Property Name

     # Terraforming
     terraform init -backend-config=storage_account_name=$(terraformBackendStorageAccount) -backend-config=container_name=$(terraformBackendContainer) -backend-config=key='$(terraformBackendBlob)' -backend-config=resource_group_name=$(terraformBackendResourceGroup)
     Invoke-Command -ScriptBlock {
       $Private:ErrorActionPreference = "Continue"
       terraform workspace new $(terraformWorkspace) 2>$null
     }
     terraform workspace select $(terraformWorkspace)
     Write-Host "terraform workspace is '$(terraform workspace show)'"
     if ([System.Convert]::ToBoolean("$(destroyAgentIfExists)")) {
       terraform destroy -auto-approve -var="devops_pat=$(TF_VAR_devops_pat)" 
     }
     terraform plan -var="devops_pat=$(TF_VAR_devops_pat)" -out='agent.plan'
     terraform apply -auto-approve 'agent.plan'
    addSpnToEnvironment: true
    useGlobalConfig: true
    workingDirectory: '$(terraformDirectory)'
    failOnStandardError: true
  env:
    # No prompts
    TF_IN_AUTOMATION: 'true' 
    TF_INPUT: 0

- task: AzureCLI@2
  displayName: 'Enable agent(s)'
  # Only enable if it was in the first place
  condition: succeeded()
  inputs:
    azureSubscription: '$(subscriptionConnection)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #$DebugPreference="Continue"
      #$InformationPreference="Continue"
      ./update_agent_status.ps1 -Enabled:$true -AgentPoolName $(TF_VAR_pipeline_agent_pool) -AgentNamePrefix $(TF_VAR_pipeline_agent_name) -Token "$(System.AccessToken)"
    addSpnToEnvironment: true
    useGlobalConfig: true
    workingDirectory: '$(scriptDirectory)'
  env:
    # Use Pipeline token to access Azure DevOps
    AZURE_DEVOPS_EXT_PAT: '$(System.AccessToken)'