#!/usr/bin/env pwsh

# This file is generated by Terraform
# https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file
# https://www.terraform.io/language/functions/templatefile


$env:FOO = "bar"
$env:SELF_HOSTED_DEMO_AGENT_OUTBOUND_IP = "20.109.225.109"
$env:SELF_HOSTED_DEMO_AGENT_SUBNET_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-agents-lusq/providers/Microsoft.Network/virtualNetworks/pipeline-test-agents-lusq-centralus-network/subnets/ScaleSetAgents"
$env:SELF_HOSTED_DEMO_AGENT_USER_ASSIGNED_IDENTITY_CLIENT_ID = "8c35ef2c-253b-4012-8f1d-ff3e5cb6053f"
$env:SELF_HOSTED_DEMO_AGENT_USER_ASSIGNED_IDENTITY_NAME = "pipeline-test-agents-lusq-agent-identity"
$env:SELF_HOSTED_DEMO_AGENT_USER_ASSIGNED_IDENTITY_PRINCIPAL_ID = "228122bb-dd16-4607-9d72-4682d1847d5b"
$env:SELF_HOSTED_DEMO_AGENT_USER_ASSIGNED_IDENTITY_RESOURCE_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-agents-lusq/providers/Microsoft.ManagedIdentity/userAssignedIdentities/pipeline-test-agents-lusq-agent-identity"
$env:SELF_HOSTED_DEMO_AGENT_VIRTUAL_NETWORK_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-agents-lusq/providers/Microsoft.Network/virtualNetworks/pipeline-test-agents-lusq-centralus-network"
$env:SELF_HOSTED_DEMO_COMPUTE_GALLERY_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/Shared/providers/Microsoft.Compute/galleries/SharedImages"
$env:SELF_HOSTED_DEMO_COMPUTE_GALLERY_NAME = "SharedImages"
$env:SELF_HOSTED_DEMO_COMPUTE_GALLERY_RESOURCE_GROUP_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/Shared"
$env:SELF_HOSTED_DEMO_COMPUTE_GALLERY_RESOURCE_GROUP_NAME = "Shared"
$env:SELF_HOSTED_DEMO_PACKER_POLICY_MANAGED_IDENTITY_CLIENT_ID = "290d839e-6625-4dd2-9e5c-246aaa532641"
$env:SELF_HOSTED_DEMO_PACKER_POLICY_MANAGED_IDENTITY_NAME = "pipeline-test-images-network-lusq-policy-identity"
$env:SELF_HOSTED_DEMO_PACKER_POLICY_MANAGED_IDENTITY_PRINCIPAL_ID = "7bc5d8a3-9a09-42ff-9797-ad705544bea2"
$env:SELF_HOSTED_DEMO_PACKER_POLICY_MANAGED_IDENTITY_RESOURCE_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-images-network-lusq/providers/Microsoft.ManagedIdentity/userAssignedIdentities/pipeline-test-images-network-lusq-policy-identity"
$env:SELF_HOSTED_DEMO_PACKER_POLICY_SET_NAME = "pipeline-build-policies-test-lusq"
$env:SELF_HOSTED_DEMO_PACKER_STORAGE_ACCOUNT_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-images-network-lusq/providers/Microsoft.Storage/storageAccounts/pplntstmgsntwrlusqpckr"
$env:SELF_HOSTED_DEMO_PACKER_STORAGE_ACCOUNT_NAME = "pplntstmgsntwrlusqpckr"
$env:SELF_HOSTED_DEMO_PACKER_STORAGE_ACCOUNT_RESOURCE_GROUP_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-images-network-lusq"
$env:SELF_HOSTED_DEMO_PACKER_STORAGE_ACCOUNT_RESOURCE_GROUP_NAME = "pipeline-test-images-network-lusq"
$env:SELF_HOSTED_DEMO_PACKER_SUBNET_NAME = "Packer"
$env:SELF_HOSTED_DEMO_PACKER_VIRTUAL_NETWORK_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-images-network-lusq/providers/Microsoft.Network/virtualNetworks/pipeline-test-images-network-lusq-centralus-network"
$env:SELF_HOSTED_DEMO_PACKER_VIRTUAL_NETWORK_NAME = "pipeline-test-images-network-lusq-centralus-network"
$env:SELF_HOSTED_DEMO_PACKER_VIRTUAL_NETWORK_RESOURCE_GROUP_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-images-network-lusq"
$env:SELF_HOSTED_DEMO_PACKER_VIRTUAL_NETWORK_RESOURCE_GROUP_NAME = "pipeline-test-images-network-lusq"
$env:SELF_HOSTED_DEMO_VHD_STORAGE_ACCOUNT_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-agents-lusq/providers/Microsoft.Storage/storageAccounts/pplntstgntslsqlusqvhd"
$env:SELF_HOSTED_DEMO_VHD_STORAGE_ACCOUNT_NAME = "pplntstgntslsqlusqvhd"
$env:SELF_HOSTED_DEMO_VHD_STORAGE_ACCOUNT_RESOURCE_GROUP_ID = "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/pipeline-test-agents-lusq"
$env:SELF_HOSTED_DEMO_VHD_STORAGE_ACCOUNT_RESOURCE_GROUP_NAME = "pipeline-test-agents-lusq"
$env:SELF_HOSTED_DEMO_VHD_STORAGE_CONTAINER_ID = "https://pplntstgntslsqlusqvhd.blob.core.windows.net/vhds"
$env:SELF_HOSTED_DEMO_VHD_STORAGE_CONTAINER_NAME = "vhds"