# This pipeline is for CI/CD
name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)

trigger: none

pr:
  autoCancel: false
  branches:
    include:
    - '*'
  drafts: false
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 0 * * Mon,Wed,Fri'
  displayName: 'Bi-Nightly build (UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - master

variables:
- group: 'agent-info'

pool:
  name: '$(pool)'
  vmImage: $(vmImage)

steps:
- pwsh: |
    Get-ChildItem -Path Env: -Recurse -Include * | Sort-Object -Property Name
  displayName: 'List environment variables'
