parameters:
- name: image
  displayName: Image
  type: string
  default: All
  values:
  - All
  - Ubuntu1804
  - Ubuntu2004
  - Windows2019
  - Windows2022

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)

resources:
  repositories:
  - repository: virtual-environments
    type: github
    endpoint: github.com # Service Connection name
    name: actions/virtual-environments
    trigger:
      branches:
        include:
        - main
      paths:
        include:
        - 'images/linux/**'
        - 'images/win/**'

trigger: none

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 0 * * Mon,Wed,Fri'
  displayName: 'Bi-Nightly build (UTC)'
  always: 'true' # Run if there are no changes
  branches:
    include:
    - master

variables:
- group: 'pipeline-agents-ci'

jobs:
- ${{ if ne(parameters.image,'All') }}:
  - template: test.yml
    parameters:
      image: ${{ parameters.image }}
      # imageResourceGroup: 'packer-$(Build.BuildId)'
      imageResourceGroup: 'packer-11420'
- ${{ else }}:
  - template: test.yml
    parameters:
      image: Ubuntu1804
      # imageResourceGroup: 'packer-$(Build.BuildId)a'
      imageResourceGroup: 'packer-11420'
  - template: test.yml
    parameters:
      image: Ubuntu2004
      # imageResourceGroup: 'packer-$(Build.BuildId)b'
      imageResourceGroup: 'packer-11420'
  - template: test.yml
    parameters:
      image: Windows2019
      # imageResourceGroup: 'packer-$(Build.BuildId)c'
      imageResourceGroup: 'packer-11420'
  - template: test.yml
    parameters:
      image: Windows2022
      # imageResourceGroup: 'packer-$(Build.BuildId)d'
      imageResourceGroup: 'packer-11420'
