# The Service Connection (Principal) for this pipeline requires Storage Data (Reader) access to the subscription
# This pipeline will create a storage account to temporarily store a VHD

parameters:
- name: image
  displayName: Image
  type: string
  default: Ubuntu
  values:
  - All
  - Latest
  - Stable
  - Ubuntu
  - Ubuntu1804
  - Ubuntu2004
  - Ubuntu2204
  - Windows
  - Windows2019
  - Windows2022
- name: destroy
  displayName: Destroy Infrastructure
  type: boolean
  default: true
- name: excludeFromLatest
  displayName: Exclude from latest
  type: boolean
  default: true
- name: numberOfVersionsToKeep
  displayName: Number of image versions to keep
  type: number
  default: 2

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-${{ lower(parameters.image) }}-$(Build.BuildId)

resources:
  repositories:
  - repository: runner-images
    type: github
    endpoint: github.com # Service Connection name
    name: actions/runner-images
    # trigger:
    #   branches:
    #     include:
    #     - main
    #   paths:
    #     include:
    #     - 'images/linux/**'
    #     - 'images/win/**'

trigger: none

pr:
  autoCancel: false
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 12 * * Fri'
  displayName: 'Weekly build (UTC)'
  always: 'true' # Run if there are no changes
  branches:
    include:
    - master

variables:
  - group: 'build-images'
  # Variable group should set these variables:
  # PIPELINE_DEMO_PACKER_LOCATION
  # PIPELINE_DEMO_COMPUTE_GALLERY_NAME
  # PIPELINE_DEMO_COMPUTE_GALLERY_RESOURCE_GROUP_NAME

jobs:
- ${{ if in(parameters.image,'All','Stable','Ubuntu','Ubuntu2004') }}:
  - template: build-image-template.yml
    parameters:
      destroy: ${{ parameters.destroy }}
      excludeFromLatest: ${{ parameters.excludeFromLatest }}
      image: Ubuntu1804
      imageReleaseName: ubuntu20
      imageResourceGroup: 'pipeline-image-$(Build.BuildId)-u20'
      numberOfVersionsToKeep: ${{ parameters.numberOfVersionsToKeep }}

- ${{ if in(parameters.image,'All','Latest','Ubuntu','Ubuntu2204') }}:
  - template: build-image-template.yml
    parameters:
      destroy: ${{ parameters.destroy }}
      excludeFromLatest: ${{ parameters.excludeFromLatest }}
      image: Ubuntu2004
      imageReleaseName: ubuntu22
      imageResourceGroup: 'pipeline-image-$(Build.BuildId)-u22'
      numberOfVersionsToKeep: ${{ parameters.numberOfVersionsToKeep }}

- ${{ if in(parameters.image,'All','Stable','Windows','Windows2019') }}:
  - template: build-image-template.yml
    parameters:
      destroy: ${{ parameters.destroy }}
      excludeFromLatest: ${{ parameters.excludeFromLatest }}
      image: Windows2019
      imageReleaseName: win19
      imageResourceGroup: 'pipeline-image-$(Build.BuildId)-w19'
      numberOfVersionsToKeep: ${{ parameters.numberOfVersionsToKeep }}

- ${{ if in(parameters.image,'All','Latest','Windows','Windows2022') }}:
  - template: build-image-template.yml
    parameters:
      destroy: ${{ parameters.destroy }}
      excludeFromLatest: ${{ parameters.excludeFromLatest }}
      image: Windows2022
      imageReleaseName: win22
      imageResourceGroup: 'pipeline-image-$(Build.BuildId)-w22'
      numberOfVersionsToKeep: ${{ parameters.numberOfVersionsToKeep }}