parameters:
- name: image
  displayName: Image
  type: string
  default: Stable
  values:
  - All
  - Latest
  - Stable
  - Ubuntu
  - Ubuntu1804
  - Ubuntu2004
  - Windows
  - Windows2019
  - Windows2022
- name: destroy
  displayName: Destroy Infrastructure
  type: boolean
  default: true

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-${{ lower(parameters.image) }}-$(Build.BuildId)

resources:
  repositories:
  - repository: virtual-environments
    type: github
    endpoint: github.com # Service Connection name
    name: actions/virtual-environments
    trigger:
      branches:
        include:
        - main
      paths:
        include:
        - 'images/linux/**'
        - 'images/win/**'

trigger: none

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 0 * * Mon,Wed,Fri'
  displayName: 'Bi-Nightly build (UTC)'
  always: 'true' # Run if there are no changes
  branches:
    include:
    - master

variables:
  - group: 'build-images'

jobs:
  - template: build-image.yml
    parameters:
      destroy: ${{ parameters.destroy }}
      image: Ubuntu1804
      imageReleaseName: ubuntu18
      imageResourceGroup: 'packer-$(Build.BuildId)-u18'
# - ${{ if in(parameters.image,'All','Stable','Ubuntu','Ubuntu1804') }}:
#   - template: build-image.yml
#     parameters:
#       destroy: ${{ parameters.destroy }}
#       image: Ubuntu1804
#       imageReleaseName: ubuntu18
#       imageResourceGroup: 'packer-$(Build.BuildId)-u18'

# - ${{ if in(parameters.image,'All','Latest','Ubuntu','Ubuntu2004') }}:
#   - template: build-image.yml
#     parameters:
#       destroy: ${{ parameters.destroy }}
#       image: Ubuntu2004
#       imageReleaseName: ubuntu20
#       imageResourceGroup: 'packer-$(Build.BuildId)-u20'

# - ${{ if in(parameters.image,'All','Stable','Windows','Windows2019') }}:
#   - template: build-image.yml
#     parameters:
#       destroy: ${{ parameters.destroy }}
#       image: Windows2019
#       imageReleaseName: win19
#       imageResourceGroup: 'packer-$(Build.BuildId)-w19'

# - ${{ if in(parameters.image,'All','Latest','Windows','Windows2022') }}:
#   - template: build-image.yml
#     parameters:
#       destroy: ${{ parameters.destroy }}
#       image: Windows2022
#       imageReleaseName: win22
#       imageResourceGroup: 'packer-$(Build.BuildId)-w22'
