# This pipeline is used to test self-hosted agents
#  e.g. to discover what outbound network access is required
parameters:
- name: boardsQueryId
  displayName: Work item query ID
  type: string
  default: '00000000-0000-0000-0000-000000000000'

trigger: none

variables:
- name: 'artifactDirectory'
  value: 'scratch'
- name: 'artifactName'
  value: 'artifactTest'
- name: 'artifactSample'
  value: 'sample.txt'
- name: pool
  value: Default

jobs:
- job: jobA
  displayName: Producer
  pool:
    name: '$(pool)'

  workspace:
    clean: all

  steps:
  - script: |
      mkdir $(artifactDirectory)
      cd $(artifactDirectory)
      echo "hello pipeline" > $(artifactSample)
    displayName: 'Prepare artifacts'

  - publish: $(artifactDirectory)
    displayName: 'Publish artifacts'
    artifact: $(artifactName)

- job: jobB
  displayName: Consumer
  dependsOn:
    - jobA
  pool:
    name: '$(pool)'

  variables:
    artifactDirectory: $(Pipeline.Workspace)/$(artifactName)

  workspace:
    clean: all

  steps:
  - download: current
    displayName: 'Download artifacts directory from previous job'
    artifact: $(artifactName)

  - script: |
      ls -al
      cat $(artifactSample)
    displayName: 'Read artifacts'
    workingDirectory: '$(artifactDirectory)'

  - ${{ if ne(coalesce(parameters.boardsQueryId,'00000000-0000-0000-0000-000000000000'),'00000000-0000-0000-0000-000000000000') }}:
    - task: queryWorkItems@0
      displayName: 'Query work items'
      inputs:
        queryId: ${{ parameters.boardsQueryId }}