# This pipeline is used to test self-hosted agents
#  e.g. to discover what outbound network access is required

trigger: none

variables:
- name: 'artifactDirectory'
  value: 'visuals'
- name: 'artifactName'
  value: 'artifactTest'
- name: 'artifactSample'
  value: 'sample.txt'
- name: pool
  value: Default

jobs:
- job: jobA
  displayName: Producer
  pool:
    name: '$(pool)'

  workspace:
    clean: all

  steps:
  - script: |
      echo "hello pipeline" > $(artifactSample)
    displayName: 'Prepare artifacts'
    workingDirectory: '$(artifactDirectory)'

  - publish: $(artifactDirectory)
    displayName: 'Publish artifacts'
    artifact: $(artifactName)

- job: jobB
  displayName: Consumer
  dependsOn:
    - jobA
  pool:
    name: '$(pool)'

  variables:
    artifactDirectory: $(Pipeline.Workspace)/$(artifactName)

  workspace:
    clean: all

  steps:
  - download: current
    displayName: 'Download artifacts directory from previous job'
    artifact: $(artifactName)

  - script: |
      ls -al
      cat $(artifactSample)
    displayName: 'Read artifacts'
    workingDirectory: '$(artifactDirectory)'
