parameters:
- name: image
  displayName: Image
  type: string
  default: Stable
  values:
  - All
  - Latest
  - Stable
  - Ubuntu
  - Ubuntu1804
  - Ubuntu2004
  - Windows
  - Windows2019
  - Windows2022
- name: destroy
  displayName: Destroy Infrastructure
  type: boolean
  default: true
- name: retryCount
  displayName: Build task retry count
  type: number
  default: 1

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-${{ lower(parameters.image) }}-$(Build.BuildId)

resources:
  repositories:
  - repository: virtual-environments
    type: github
    endpoint: github.com # Service Connection name
    name: actions/virtual-environments
    trigger:
      branches:
        include:
        - main
      paths:
        include:
        - 'images/linux/**'
        - 'images/win/**'

trigger: none

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 0 * * Mon,Wed,Fri'
  displayName: 'Bi-Nightly build (UTC)'
  always: 'true' # Run if there are no changes
  branches:
    include:
    - master

variables:
  - group: 'build-images'
  - name: SYSTEM_DEBUG
    value: 'true'
jobs:
- template: build-image.yml
  parameters:
    destroy: false
    image: Ubuntu2004
    imageReleaseName: ubuntu20
    imageResourceGroup: 'packer-11990-u20'
    retryCount: 0
