parameters:
- name: waitForReplication
  displayName: Wait for image replication to finish
  type: boolean
  default: true

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)

resources:
  repositories:
  - repository: virtual-environments
    type: github
    endpoint: github.com # Service Connection name
    name: actions/virtual-environments
    trigger:
      branches:
        include:
        - main
      paths:
        include:
        - 'images/linux/**'
        - 'images/win/**'

trigger: none

pr:
  autoCancel: false
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 2 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true' # Run if there are no changes
  branches:
    include:
    - master

variables:
  - group: 'build-images-isolated'

jobs:
  - template: build-image-isolated-template.yml
    parameters:
      destroy: true
      image: Ubuntu2004
      imageReleaseName: ubuntu20
      imageResourcePrefix: 'packer12850u20'
      retryCount: 1
      waitForReplication: {{ parameters.waitForReplication }}
