write_files:
- path: /etc/environment
  content: |
    GEEKZTER_AGENT_SUBNET_ID="${subnet_id}"
    GEEKZTER_AGENT_VIRTUAL_NETWORK_ID="${virtual_network_id}"
    GEEKZTER_AGENT_OUTBOUND_IP="${outbound_ip}"
  append: true

runcmd:
  # User configuration
  - chown -R ${user_name}:${user_name} /home/${user_name}
