packages:
  - nfs-common

runcmd:
  # Point diagnostics to NFS
  - echo creating mount point ${mount_point}...
  - mkdir -p ${mount_point}
  - mount -t nfs ${nfs_share} ${mount_point} -o vers=4,minorversion=1,sec=sys
  - mkdir -p ${mount_point}/$(hostname) 2>/dev/null
  - mkdir -p $(dirname ${diagnostics_directory})
  - ln -s ${mount_point}/$(hostname) ${diagnostics_directory}
  - chown ${user}:${user} ${mount_point}/$(hostname)
  - echo "${nfs_share}  ${mount_point}    nfs   vers=4,minorversion=1,sec=sys   0   2" | sudo tee -a /etc/fstab 
  - echo mounted ${nfs_share} to ${mount_point}, linked ${mount_point}/$(hostname) to ${diagnostics_directory}
