packages:
  - curl 
  - dos2unix 
  - jq 
  - sed

write_files:
- path: /home/${user}/install_agent.sh
  append: false
  content: ${install_agent_script_b64}
  encoding: b64

runcmd:
  - dos2unix /home/${user}/install_agent.sh
  - sudo chmod +x /home/${user}/install_agent.sh
  - sudo chown ${user}:${user} /home/${user}
  - sudo chown ${user}:${user} /home/${user}/install_agent.sh
  - sudo -u ${user} /home/${user}/install_agent.sh --agent-name ${agent_name} --agent-pool ${agent_pool} --agent-version-id ${agent_version_id} --org ${org} --pat ${pat}
  # https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md#post-generation-scripts
# - [ -d /opt/post-generation ] && sudo "find /opt/post-generation -mindepth 1 -maxdepth 1 -type f -name '*.sh' -exec bash {} \;"

final_message: "Installed Pipeline Agent $UPTIME seconds into cloud-init"