runcmd:
# https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#post-generation-scripts
- echo Post generation
- sudo su -c whoami ${user_name}
- '[ -d /opt/post-generation ] && sudo su -c "find /opt/post-generation -mindepth 1 -maxdepth 1 -type f -name *.sh -exec bash {} \;"'
- '[ -d /opt/post-generation ] && [ -x "$(command -v dockerd)" ] && sudo usermod -aG docker ${user_name}'
