#!/usr/bin/env pwsh
<# 
.SYNOPSIS 
    This file is generated by Terraform
    https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file
    https://www.terraform.io/language/functions/templatefile
    Use this to troubleshoot scripts as if they would run on a pipeline agent, where these variables are also set
#> 

%{ for name, value in environment }
$env:${name} = "${value}"%{ endfor ~}